// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: baseStruct.proto

package baseStruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyID         int32  `protobuf:"varint,1,opt,name=keyID,proto3" json:"keyID,omitempty"`                 //属性ID（结构内）
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                    //属性名称 （结构内唯一）
	AttributeType int32  `protobuf:"varint,3,opt,name=attributeType,proto3" json:"attributeType,omitempty"` //属性类型
	Des           string `protobuf:"bytes,4,opt,name=des,proto3" json:"des,omitempty"`                      //属性描述
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baseStruct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_baseStruct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_baseStruct_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetKeyID() int32 {
	if x != nil {
		return x.KeyID
	}
	return 0
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetAttributeType() int32 {
	if x != nil {
		return x.AttributeType
	}
	return 0
}

func (x *Attribute) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type EntityStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyID int32                `protobuf:"varint,1,opt,name=keyID,proto3" json:"keyID,omitempty"`                                                                                       //结构ID
	Name  string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                          //结构名字
	Data  map[int32]*Attribute `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //结构的属性
}

func (x *EntityStruct) Reset() {
	*x = EntityStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baseStruct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityStruct) ProtoMessage() {}

func (x *EntityStruct) ProtoReflect() protoreflect.Message {
	mi := &file_baseStruct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityStruct.ProtoReflect.Descriptor instead.
func (*EntityStruct) Descriptor() ([]byte, []int) {
	return file_baseStruct_proto_rawDescGZIP(), []int{1}
}

func (x *EntityStruct) GetKeyID() int32 {
	if x != nil {
		return x.KeyID
	}
	return 0
}

func (x *EntityStruct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityStruct) GetData() map[int32]*Attribute {
	if x != nil {
		return x.Data
	}
	return nil
}

type AvatarStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyID int32                   `protobuf:"varint,1,opt,name=keyID,proto3" json:"keyID,omitempty"`                                                                                       //avatarID
	Name  string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                          //avatar名字
	Data  map[int32]*EntityStruct `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //avatar的属性表
}

func (x *AvatarStruct) Reset() {
	*x = AvatarStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baseStruct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarStruct) ProtoMessage() {}

func (x *AvatarStruct) ProtoReflect() protoreflect.Message {
	mi := &file_baseStruct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarStruct.ProtoReflect.Descriptor instead.
func (*AvatarStruct) Descriptor() ([]byte, []int) {
	return file_baseStruct_proto_rawDescGZIP(), []int{2}
}

func (x *AvatarStruct) GetKeyID() int32 {
	if x != nil {
		return x.KeyID
	}
	return 0
}

func (x *AvatarStruct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvatarStruct) GetData() map[int32]*EntityStruct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_baseStruct_proto protoreflect.FileDescriptor

var file_baseStruct_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x22, 0x6d, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6b, 0x65, 0x79, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x65, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x53, 0x0a, 0x09, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xcd, 0x01, 0x0a, 0x0c, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6b, 0x65, 0x79, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x56, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x33, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69,
	0x6b, 0x65, 0x71, 0x69, 0x61, 0x6f, 0x2f, 0x65, 0x61, 0x73, 0x79, 0x53, 0x74, 0x75, 0x64, 0x79,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_baseStruct_proto_rawDescOnce sync.Once
	file_baseStruct_proto_rawDescData = file_baseStruct_proto_rawDesc
)

func file_baseStruct_proto_rawDescGZIP() []byte {
	file_baseStruct_proto_rawDescOnce.Do(func() {
		file_baseStruct_proto_rawDescData = protoimpl.X.CompressGZIP(file_baseStruct_proto_rawDescData)
	})
	return file_baseStruct_proto_rawDescData
}

var file_baseStruct_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_baseStruct_proto_goTypes = []interface{}{
	(*Attribute)(nil),    // 0: game.baseStruct.Attribute
	(*EntityStruct)(nil), // 1: game.baseStruct.EntityStruct
	(*AvatarStruct)(nil), // 2: game.baseStruct.AvatarStruct
	nil,                  // 3: game.baseStruct.EntityStruct.DataEntry
	nil,                  // 4: game.baseStruct.AvatarStruct.DataEntry
}
var file_baseStruct_proto_depIdxs = []int32{
	3, // 0: game.baseStruct.EntityStruct.data:type_name -> game.baseStruct.EntityStruct.DataEntry
	4, // 1: game.baseStruct.AvatarStruct.data:type_name -> game.baseStruct.AvatarStruct.DataEntry
	0, // 2: game.baseStruct.EntityStruct.DataEntry.value:type_name -> game.baseStruct.Attribute
	1, // 3: game.baseStruct.AvatarStruct.DataEntry.value:type_name -> game.baseStruct.EntityStruct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_baseStruct_proto_init() }
func file_baseStruct_proto_init() {
	if File_baseStruct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_baseStruct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_baseStruct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_baseStruct_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_baseStruct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_baseStruct_proto_goTypes,
		DependencyIndexes: file_baseStruct_proto_depIdxs,
		MessageInfos:      file_baseStruct_proto_msgTypes,
	}.Build()
	File_baseStruct_proto = out.File
	file_baseStruct_proto_rawDesc = nil
	file_baseStruct_proto_goTypes = nil
	file_baseStruct_proto_depIdxs = nil
}
